{% set name = "tt-metalium" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tenstorrent/tt-metal/releases/download/v{{ version.replace(".rc", "-rc") }}/tt-metalium.tar.gz
  sha256: 1574e0c3b0c624290b23e9e4a6dbe2b13d89fd1e1f840cccc4ee9a178c12b2a9

build:
  number: 0
  skip: true  # [not linux or py==39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - git

  host:
    - python
    - pip
    - wheel
    - setuptools
    - numactl
    - libhwloc
    - mpc
    - numpy
    - loguru
    - networkx
    - pytorch
    - python-graphviz

  run:
    - python
    - numactl
    - libhwloc
    - libzlib
    - mpfr
    - gmp
    - mpc
    - numpy
    - loguru
    - networkx
    - pytorch
    - python-graphviz

about:
  home: https://github.com/tenstorrent/tt-metal
  summary: 'Simple, fast, extensible runtime libraries for Tenstorrent Hardware'
  description: |
    TT-NN operator library, and TT-Metalium low level kernel programming model.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  doc_url: https://docs.tenstorrent.com/tt-metalium/latest
  dev_url: https://github.com/tenstorrent/tt-metal

extra:
  recipe-maintainers:
    - blozano-tt
    - afuller-TT
